spring:
  redis:
    timeout: 6000ms
    password:
#    sentinel: # 配置哨兵模式
#      master: # 主节点
#      nodes: # 从节点
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 127.0.0.1:8001
        - 127.0.0.1:8002
        - 127.0.0.1:8003
        - 127.0.0.1:8004
        - 127.0.0.1:8005
        - 127.0.0.1:8006
#    pool: # 使用系统默认连接池
#      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#      max-idle: 10    # 连接池中的最大空闲连接
#      max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      min-idle:  5     # 连接池中的最小空闲连接
#      timeout: 6000  # 连接超时时长（毫秒）

#    jedis: # 使用 jedis 连接池
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接

    lettuce: # 使用 lettuce 连接池
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）